version: "3.9"

services:
  mysql:
    image: mysql:8.0.44
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: p4_back_2025
      MYSQL_USER: app_user
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
